language: objective-c
python:
  - "2.7"
osx_image: xcode7
xcode_project: Owncloud iOs Client.xcodeproj
xcode_scheme: Owncloud iOs Client
xcode_sdk: iphonesimulator

install:
  - npm install appium
  - python setup.py install
  
before_script:
  - brew update; brew update
  - chmod +x automation_Test/loginTest.py

addons:
  sauce_connect: true

script:
  - node node_modules/appium &
  - python automation_Test/loginTest.py
